name: Build & Deploy API

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        type: string

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'Services/API/Todo.API/**'
              - '.github/workflows/api.yml'
              - '.github/workflows/main.yml'

  build-api:
    needs: check-changes
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    env:
      FRONTEND_URL: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore NuGet packages
        working-directory: Services/API/Todo.API
        run: dotnet restore

      # -----------------------------
      # Build & Push Docker Image
      # -----------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_IMAGE}} \
            -f DevOps/Build/API/ASPNET/Dockerfile.production .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_IMAGE}}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false
          allow-no-subscriptions: true

      - name: Get Terraform Workspace Outputs
        uses: hashicorp/tfc-workflows-github/actions/workspace-output@v1.3.2
        id: tf_outputs
        with:
          organization: amiasea
          workspace: todo-${{ inputs.target_env }}
          token: ${{ secrets.TF_HCP_API_TOKEN }}

      - name: Set FRONTEND_URL Environment Variable
        shell: pwsh
        run: |
          $raw = '${{ steps.tf_outputs.outputs.outputs }}' | ConvertFrom-Json

          # Convert array â†’ map
          $map = @{}
          foreach ($item in $raw) {
            $map[$item.name] = $item.value
          }

          echo "FRONTEND_URL=$($map['frontend_app_fqdn'])" >> $env:GITHUB_ENV

      - name: Update API Azure Container App Settings
        uses: azure/cli@v1
        with:
          inlineScript: |
            az containerapp update \
              --name "${{ vars.AZURE_API_CONTAINER_APP_NAME }}-${{ inputs.target_env }}" \
              --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}-${{ inputs.target_env }}" \
              --set-env-vars FRONTEND_URL="${{ env.FRONTEND_URL }}"
      