name: Build & Upload React Artifact

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        type: string
      api_url:
        description: 'API base URL from Terraform'
        required: true
        type: string
      react_url:
        description: 'React Static Web App URL from Terraform'
        required: false
        type: string
      frontend_client_id:
        description: 'Frontend app registration client ID'
        required: false
        type: string
      api_client_id:
        description: 'API app registration client ID'
        required: false
        type: string
      api_scope_uri:
        description: 'API scope URI for authentication'
        required: false
        type: string
env:
  WEB_PATH: 'Services/Web/React/todo'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - "${{ env.WEB_PATH }}/**"
              - '.github/workflows/build-react.yml'

  build-react:
    needs: check-changes
    if: needs.check-changes.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache React Build
        uses: actions/cache@v4
        with:
          path: "${{ env.WEB_PATH }}/dist"
          # Hardcoded to avoid critical bug with hashFiles
          key: ${{ runner.os }}-react-${{ hashFiles(format('{0}/**', 'Services/Web/React/todo/**')) }}
          restore-keys: |
            ${{ runner.os }}-react-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.11.1'
      
      - name: Install dependencies
        working-directory: ${{ env.WEB_PATH }}
        run: npm ci 

      - name: Build React app
        working-directory: ${{ env.WEB_PATH }}
        env:
          VITE_API_BASE_URL: ${{ inputs.api_url }}/api
          VITE_CLIENT_ID: ${{ inputs.frontend_client_id }}
          VITE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          VITE_REDIRECT_URI: ${{ inputs.react_url }}
          VITE_POST_LOGOUT_REDIRECT_URI: ${{ inputs.react_url }}
          VITE_API_SCOPE_URI: ${{ inputs.api_scope_uri }}
        run: npm run build

      - name: Upload React artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-${{ inputs.target_env }}
          path: ${{ env.WEB_PATH }}/dist
          retention-days: 1