name: Deploy Frontend (Docker)

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        type: string
      api_url:
        description: 'API base URL from Terraform'
        required: true
        type: string

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check for Frontend Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'Services/Web/Angular/todo/**'
              - 'Services/Web/React/todo/**'
              - 'DevOps/Infrastructure/**'
              - '.github/workflows/main.yml'
              - '.github/workflows/deploy-frontend.yml'

  deploy-frontend:
    needs: check-changes
    if: needs.check-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # -----------------------------
      # Build Angular
      # -----------------------------
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Build Angular
        working-directory: Services/Web/Angular/todo
        run: |
          bun install --frozen-lockfile
          bun run build -- --configuration production

      # -----------------------------
      # Build React
      # -----------------------------
      - name: Build React
        working-directory: Services/Web/React/todo
        run: |
          bun install --frozen-lockfile
          bun run build -- --mode production

      # -----------------------------
      # Build & Push Docker Image
      # -----------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest \
            -f DevOps/Infrastructure/Dockerfile.production .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      - name: 'Azure Frontend App Service Settings'
        uses: Azure/appservice-settings@v1
        with:
          app-name: "${{ vars.AZURE_FRONTEND_APP_SERVICE_NAME }}-${{ inputs.target_env }}"
          app-settings-json: |
            [
              {
                "name": "API_BASE_URL",
                "value": "${{ inputs.api_url }}"
              }
            ]