name: Deploy API

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        type: string
      frontend_url:
        description: 'FRONTEND_URL application setting value'
        required: true
        type: string
  
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'Services/API/Todo.API/**'
              - '.github/workflows/deploy-api.yml'
              - '.github/workflows/build-api.yml'
              - '.github/workflows/main.yml'
              - 'DevOps/Infrastructure/**'
              
  deploy-api:
    needs: check-changes
    if: needs.check-changes.outputs.api_changed == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-${{ inputs.target_env }}
          path: api_artifact

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false
          allow-no-subscriptions: true

      - name: 'Azure API App Service Settings'
        uses: Azure/appservice-settings@v1
        with:
          app-name: "${{ vars.AZURE_API_APP_SERVICE_NAME }}-${{ inputs.target_env }}"
          # slot-name: staging
          app-settings-json: |
            [
              {
                "name": "FRONTEND_URL",
                "value": "${{ inputs.frontend_url }}"
              }
            ]


      - name: Deploy API to Azure Web App (Linux)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ vars.AZURE_API_APP_SERVICE_NAME }}-${{ inputs.target_env }}"
          # slot-name: staging
          package: api_artifact
          clean: true

      # - name: Swap staging to production
      #   uses: azure/cli@v1
      #   with:
      #     inlineScript: |
      #       az webapp deployment slot swap \
      #         --resource-group "${{ vars.AZURE_RESOURCE_GROUP }}-${{ inputs.target_env }}" \
      #         --name "${{ vars.AZURE_API_APP_SERVICE_NAME }}-${{ inputs.target_env }}" \
      #         --slot staging \
      #         --target-slot production
      