name: Terraform Infrastructure

on:
  workflow_call:
    inputs:
      target_env:
        description: 'Target environment'
        required: true
        type: string
    outputs:
      api_url:
        description: "API App Service URL"
        value: ${{ jobs.terraform.outputs.api_url }}
      frontend_url:
        description: "Frontend App Service URL"
        value: ${{ jobs.terraform.outputs.frontend_url }}
      frontend_client_id:
        description: "Frontend App Registration Client ID"
        value: ${{ jobs.terraform.outputs.frontend_client_id }}
      api_client_id:
        description: "API App Registration Client ID"
        value: ${{ jobs.terraform.outputs.api_client_id }}
      api_scope_uri:
        description: "API OAuth Scope URI"
        value: ${{ jobs.terraform.outputs.api_scope_uri }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_env }}
    permissions:
      id-token: write
      contents: read
    env:
      TERRAFORM_DIR: DevOps/Infrastructure/Terraform
      TF_VAR_api_build_configuration: ${{ vars.API_BUILD_CONFIGURATION }}
      TF_VAR_target_env: ${{ inputs.target_env }}
      TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_WORKSPACE: "todo-${{ inputs.target_env }}"
      TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      TV_VAR_frontend_image: ${{ vars.FRONTEND_IMAGE }}
    outputs:
      tenant_id: ${{ steps.terraform_output.outputs.tenant_id }}
      api_url: ${{ steps.terraform_output.outputs.api_url }}
      frontend_url: ${{ steps.terraform_output.outputs.frontend_url }}
      frontend_client_id: ${{ steps.terraform_output.outputs.frontend_client_id }}
      api_client_id: ${{ steps.terraform_output.outputs.api_client_id }}
      api_scope_uri: ${{ steps.terraform_output.outputs.api_scope_uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_HCP_API_TOKEN }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: terraform_output
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          API_URL=$(terraform output -raw api_app_service_default_url)
          FRONTEND_URL=$(terraform output -raw frontend_app_service_default_url)
          FRONTEND_CLIENT_ID=$(terraform output -raw frontend_app_id)
          API_CLIENT_ID=$(terraform output -raw api_app_registration_app_id)
          TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          API_SCOPE_URI=$(terraform output -raw api_scope_uri)
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "frontend_url=$FRONTEND_URL" >> $GITHUB_OUTPUT
          echo "frontend_client_id=$FRONTEND_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "api_client_id=$API_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "tenant_id=$TENANT_ID" >> $GITHUB_OUTPUT
          echo "api_scope_uri=$API_SCOPE_URI" >> $GITHUB_OUTPUT